using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyWater.Notifications.Infrastructure.Persistence.Entities;

/// <summary>1:1 copy of notification.notifications (created by ms-notification-db). Not the domain entity.</summary>
[Table("notifications", Schema = "notification")]
public sealed class NotificationEntity
{
    /// <summary>Created by the domain: never generated by the database.</summary>
    [Key, Column("id"), DatabaseGenerated(DatabaseGeneratedOption.None)] public Guid Id { get; set; }
    [Column("user_id")] public Guid? UserId { get; set; }
    [Column("role")] public string? Role { get; set; }
    [Column("type")] public string Type { get; set; } = "";
    [Column("severity")] public string Severity { get; set; } = "INFO";
    [Column("title")] public string Title { get; set; } = "";
    [Column("body")] public string Body { get; set; } = "";
    [Column("place_id")] public Guid? PlaceId { get; set; }
    [Column("source_event_id")] public string? SourceEventId { get; set; }
    [Column("created_at")] public DateTime CreatedAt { get; set; }
}

/// <summary>1:1 copy of notification.notification_reads (key: notification_id + user_id).</summary>
[Table("notification_reads", Schema = "notification")]
public sealed class NotificationReadEntity
{
    [Column("notification_id")] public Guid NotificationId { get; set; }
    [Column("user_id")] public Guid UserId { get; set; }
    [Column("read_at")] public DateTime ReadAt { get; set; }
}
